### PR TITLE
Add custom prefixes

### PR DESCRIPTION
**Pull request by TimurSultanov**
Added an ability to add custom prefixes to the validator.

### CODE REVIEW

**Comment by radarlog** [comment]
@TimurSultanov thank you for the contribution.

The [GTIN specification](https://www.gs1.org/standards/barcodes-epcrfid-id-keys/gs1-general-specifications) has [defined](https://github.com/real-digital/gtin-validator/blob/master/src/Gtin.php#L86) all possible prefixes in a very [precise](https://github.com/real-digital/gtin-validator/blob/master/src/Gtin/Specification/Prefix.php#L11) way.

What's the purpose of you PR?

**Comment by TimurSultanov** [comment]
@radarlog We should use some custom prefixes in our company, for example "250"
One vendor creates GtINs with this prefix, and we should handle this situation.
Perhaps in the future we will have more custom prefixes.

**Comment by radarlog** [comment]
According to the [current](https://github.com/real-digital/gtin-validator/blob/master/src/Gtin/Specification/Prefix.php#L140) implementation prefixes from the range 200-299 are _used to issue Restricted Circulation Numbers within a company_. According to the actual specification from above it still so (please check Figure 1.4.3-1)

**Comment by TimurSultanov** [comment]
I see, but we need these prefixes for internal using.

**Comment by radarlog** [comment]
Current implementation follows the GTIN specification as strict as possible.

Since you propose something very internal and specific to your business, I cannot accept your changes into the upstream.

I would rather suggest you to fork the library and adjust it according to your needs (as you already have actually [done](https://github.com/TimurSultanov/gtin-validator)).

Hope for your understanding!

**Comment by TimurSultanov** [comment]
Thank you

**Pull request closed without merging**
