### PR TITLE
Adds PHP 8 support, fixes tests namespace

### PR DESCRIPTION
**Pull request by emielmolenaar**
Ran tests with PHP 8.0.5, did not ran into any problems.

### CODE REVIEW

**Comment by emielmolenaar** [comment]
@radarlog It would be great if you could merge and tag this 😄

**Comment by emielmolenaar** [comment]
@radarlog I hope your are doing well and find some time to merge this one. Thanks!

**Comment by radarlog** [comment]
Hi @emielmolenaar and thank you for your patience.

I'll close your PR in favor of #13, that has just been merged.

**Comment by emielmolenaar** [comment]
Nice work, thanks!

**Pull request closed without merging**
